### ISSUE TITLE
iOS9 Notifications

### ISSUE THREAD

**Issue by TeakayAero** [KWCSSA/cssams-servable#2]
Well.. The app shows there are 3 notifications, and I know theres none.. 
I can't get rid off the "3" beside the icon now.

I personally don't think the app needs a notification system for now, since it's only giving notifications after someone commenting on the wallpost you wrote. 

What do you think?

**Comment by tangdian** [comment]
Well, this is a problem. Personally I also have the "3" beside my icon and I cannot get rid of it... Even after I update the version or reinstall... I will research for solutions, thank you for letting me know that you are also having the issue.

I think notification system is necessary, and I will give more power to that later.

**Comment by TeakayAero** [comment]
The interesting thing is though I turned on the notification, it didn't give me one when I'm on my home screen (there should be one). And the notification message showed out after I clicked in the app.

It's in my notif'n history tho (if you pull down the list from top, the message is actually in there (even after I read the message (this is like if you receive a msg on wechat desktop, you will still receive a mobile one on your phone)))

I never say it's not necessary, I was suggesting for now it should be turned off for now since ppl might get annoyed by it and I guess it's not on the top of the priority queue. You can always re-active it if you feels like you wanna add more to it. 

Well, I actually have no idea about the priorities.

**Comment by tangdian** [comment]
Thanks again for reporting. This is a strange behaviour. Don't know if it is specifically for iOS 9. I will ask more people to test and see if it is an issue for iOS 10, and try to fix it.

And thank you for the suggestion, I will think about that!

**Comment by tangdian** [comment]
I found the solution to this problem. It will be fixed in next version (probably online tomorrow). Thanks for reporting again!
