### ISSUE TITLE
login E-mail Case sensitive

### ISSUE THREAD

**Issue by TeakayAero** [KWCSSA/cssams-servable#3]
According to my knowledge, the email shouldn't be case sensitive.

if I use HELLOWOLRD@uwaterloo.ca to register, then
helloworld@uwaterloo.ca should be fine for logging in.

In my case, since stupid Apple input always automatically capitalize the first character, I always type in my email with first letter capitalized, and I have to change it to lower-case since it can't let me login otherwise.

**Comment by tangdian** [comment]
Thank you, we acknowledged this issue and are working to fix that.

**Comment by tangdian** [comment]
Fixed. Thanks again for reporting!
